# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 31
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - ANNOUNCEMENT%20%3Ascream%3A

# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed soon.
  If you still have a problem, make a PR with a test case or to prove that you have tried to fix the problem.
  Notice that only bugs in the rxdb [premium plugins](https://rxdb.info/premium) are ensured to be fixed by the maintainer. Everything else
  is expected to be fixed by the community, likely you must fix it by yourself.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: "Issues are autoclosed after some time. If you still have a problem, make a PR with a test case or to prove that you have tried to fix the problem."


# https://github.com/probot/stale/blob/7510fac863900a98057436d308e9fe21bbe314ec/README.md?plain=1#L66
only: issues
